import Head from 'next/head';
import Image from 'next/image';
import {Inter} from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Header from '@/components/Header';
import Banner from '@/components/Banner';
import {IExploreData} from '@/interfaces/exploreData';
import SmallCard from '@/components/SmallCard';

const inter = Inter({subsets: ['latin']});
interface IHomeProps {
  exploreData: IExploreData;
}

export default function Home({exploreData}: IHomeProps) {
  return (
    <>
      <Head>
        <title>Airbnb</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Banner />
      <main className={'max-w-7xl mx-auto px-4'}>
        <section className={'pt-[30px]'}>
          <h2 className={'text-4xl font-semibold pb-5'}> Explore Nearby</h2>
        </section>
        <div className={'flex flex-wrap justify-between'}>
          {exploreData.items.map(({img, location, distance}, index) => {
            return (
              <SmallCard
                key={`${img}_${index}`}
                distance={distance}
                img={img}
                location={location}
              />
            );
          })}
        </div>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const exploreData = await fetch('https://www.jsonkeeper.com/b/4G1G').then(
    res => res.json(),
  );
  return {
    props: {
      exploreData: {items: exploreData},
    },
  };
};
